In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('used_cars_messy.csv')

In [22]:
df.head(16)

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Renault Duster,Renault,Duster,7,67647.0,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,Maruti Wagon R,Maruti,Wagon R,3,52000.0,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,Honda City,Honda,City,3,48959.0,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,Mahindra Scorpio,Mahindra,Scorpio,6,82000.0,dealer,Diesel,Manual,15.40,2179.0,NaN,8.0,925000.0
4,Mahindra XUV500,Mahindra,XUV500,4,34000.0,Dealer,Diesel,Automatic,16.00,2179.0,140.00,7.0,1175000.0
5,Hyundai i10,Hyundai,i10,12,73000.0,Dealer,Petrol,Manual,20.36,1197.0,78.90,5.0,190000.0
6,Hyundai i20,Hyundai,i20,12,88000.0,Dealer,Petrol,Manual,18.50,NaN,80.00,5.0,275000.0
7,Maruti Wagon R,Maruti,Wagon R,7,50000.0,Individual,Petrol,Manual,20.51,NaN,67.04,5.0,351000.0
8,Ford Freestyle,Ford,Freestyle,2,30000.0,individual,Diesel,Manual,24.40,1498.0,98.63,5.0,775000.0
9,Maruti Swift Dzire,Maruti,Swift Dzire,10,75220.0,Dealer,Diesel,Manual,19.30,1248.0,73.90,5.0,390000.0
10,Maruti Swift,Maruti,Swift,6,34000.0,Dealer,Petrol,Manual,16.10,1197.0,85.00,5.0,450000.0
11,Hyundai Grand,Hyundai,Grand,1,15000.0,Individual,Petrol,Manual,NaN,1197.0,81.86,5.0,511000.0
12,Jeep Compass,Jeep,Compass,4,43726.0,Dealer,Diesel,Manual,17.10,1956.0,173.00,5.0,1625000.0
13,Hyundai Grand,Hyundai,Grand,5,13000.0,Dealer,Petrol,Manual,18.90,1197.0,82.00,5.0,455000.0
14,Maruti Swift,Maruti,Swift,5,47350.0,Individual,Diesel,Manual,25.20,NaN,74.00,5.0,640000.0
15,Mahindra Scorpio,Mahindra,Scorpio,10,15000.0,Individual,Diesel,Manual,15.40,2179.0,120.00,8.0,700000.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15661 non-null  int64
 1   car_name           15661 non-null  object
 2   brand              15661 non-null  object
 3   model              15661 non-null  object
 4   vehicle_age        15661 non-null  int64
 5   km_driven          15661 non-null  object
 6   seller_type        15661 non-null  object
 7   fuel_type          15661 non-null  object
 8   transmission_type  15661 non-null  object
 9   mileage            14376 non-null  object
 10  engine             13792 non-null  float64
 11  max_power          14862 non-null  float64
 12  seats              15218 non-null  float64
 13  selling_price      15503 non-null  float64
dtypes: float64(4), int64(2), object(8)
memory usage: 1.7+ MB

In [6]:
df.describe()

,Unnamed: 0,vehicle_age,engine,max_power,seats,selling_price
count,15661.000000,15661.000000,13792.000000,14862.000000,15218.000000,1.550300e+04
mean,9808.189643,6.036843,1480.489342,100.513582,5.324418,1.032764e+06
std,5642.981540,3.015072,511.446057,42.854632,0.805993,1.607380e+07
min,0.000000,0.000000,793.000000,38.400000,0.000000,5.000000e+02
25%,4901.000000,4.000000,1197.000000,74.000000,5.000000,3.850000e+05
50%,9858.000000,6.000000,1248.000000,88.500000,5.000000,5.550000e+05
75%,14666.000000,8.000000,1582.000000,117.300000,5.000000,8.250000e+05
max,19543.000000,29.000000,6592.000000,626.000000,9.000000,1.000000e+09

In [8]:
df.shape

(15661, 14)

#converted Km_driven , mileage columns in to numeric

In [10]:
df['km_driven'] = pd.to_numeric(df['km_driven'], errors = "coerce")

In [15]:
df['mileage'] = pd.to_numeric(df['mileage'], errors = "coerce")

drop the Unnamed:0 column

In [20]:
df = df.drop('Unnamed: 0', axis=1)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15661 non-null  object
 1   brand              15661 non-null  object
 2   model              15661 non-null  object
 3   vehicle_age        15661 non-null  int64
 4   km_driven          15411 non-null  float64
 5   seller_type        15661 non-null  object
 6   fuel_type          15661 non-null  object
 7   transmission_type  15661 non-null  object
 8   mileage            14176 non-null  float64
 9   engine             13792 non-null  float64
 10  max_power          14862 non-null  float64
 11  seats              15218 non-null  float64
 12  selling_price      15503 non-null  float64
dtypes: float64(6), int64(1), object(6)
memory usage: 1.6+ MB

#Task 2:

In [23]:
df.isnull().sum()

car_name                0
brand                   0
model                   0
vehicle_age             0
km_driven             250
seller_type             0
fuel_type               0
transmission_type       0
mileage              1485
engine               1869
max_power             799
seats                 443
selling_price         158
dtype: int64

In [24]:
#Dropping null values from target column
df = df.dropna(subset=['selling_price'])

In [26]:
df.isnull().sum()

car_name                0
brand                   0
model                   0
vehicle_age             0
km_driven             250
seller_type             0
fuel_type               0
transmission_type       0
mileage              1468
engine               1852
max_power             791
seats                 438
selling_price           0
dtype: int64

In [27]:
#Impute missing input features
numeric_cols = df.select_dtypes(include=['number']).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

In [29]:
#For categorical features with mode
categorical_cols = df.select_dtypes(include=['object']).columns
df[categorical_cols] = df[categorical_cols].fillna(df[categorical_cols].mode())

In [31]:
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

Strip and Lowercase the "Brand" Column

In [32]:
df['brand'] = df['brand'].str.strip().str.lower()

In [33]:
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Renault Duster,renault,Duster,7,67647.0,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,Maruti Wagon R,maruti,Wagon R,3,52000.0,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,Honda City,honda,City,3,48959.0,Dealer,Petrol,Manual,19.67,1497.0,117.60,5.0,875000.0
3,Mahindra Scorpio,mahindra,Scorpio,6,82000.0,dealer,Diesel,Manual,15.40,2179.0,88.50,8.0,925000.0
4,Mahindra XUV500,mahindra,XUV500,4,34000.0,Dealer,Diesel,Automatic,16.00,2179.0,140.00,7.0,1175000.0

Extract Numeric Values from "Mileage"

In [35]:
df['mileage'] = df['mileage'].str.replace(',',  '').str.extract('(\d+)'.astype(float))

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_15290/2126626078.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['mileage'] = df['mileage'].str.replace(',',  '').str.extract('(\d+)'.astype(float))

AttributeError: Can only use .str accessor with string values!

In [36]:
print(df['mileage'].dtype)

float64

In [37]:
#remove duplicates
df = df.drop_duplicates()

#Task 3:

In [39]:
#Calculate the Mean Selling Price
y_mean = df['selling_price'].mean()
print(y_mean)

1038274.1988446136

In [43]:
#Create Baseline Predictions
y_pred_baseline = [y_mean] * len(df)
print(y_pred_baseline)

[np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136), np.float64(1038274.1988446136),

In [44]:
#Calculate and Print MAE
from sklearn.metrics import mean_absolute_error

#calculate mae
baseline_mae = mean_absolute_error(df['selling_price'], y_pred_baseline)

In [45]:
print(f"Mean selling_price: {y_mean:.2f}")
print(f"Baseline MAE: {baseline_mae:.2f}")

Mean selling_price: 1038274.20
Baseline MAE: 870039.27